application: panoptes-survey
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: piaa-dashboard

handlers:
- url: /images
  static_dir: images
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: home.app