sudo: required
language: python
python:
  - "3.4"
  - "3.5"
cache:
  - pip
before_install:
    - pip install coveralls
    - pip install -U pip
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION matplotlib pandas pytest numpy scipy
  - source activate test-environment

  - pip -q install git+http://github.com/panoptes/POCS.git#egg=pocs --no-deps
  - pip install -r requirements.txt
  - python setup.py install
script:
  - coverage run --source=piaa setup.py test
after_success:
    - if [[ $ENV == python=3.5* ]]; then
          coveralls;
      fi
