apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
    name: combiner
    labels:
        app: piaa
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: piaa
        spec:
            containers:
            - name: piaa 
              image: gcr.io/panoptes-survey/piaa:latest
              imagePullPolicy: Always
              ports: 
              - containerPort: 8080
                name: "http"
