apiVersion: v1
kind: Service
metadata:
    name: piaa
    labels:
        app: piaa 
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8080
      name: "http"
    selector:
        app: piaa
